# Core Objects

Series $\rightarrow$ 1-dimensional labeled array (like a single column)

DataFrame $\rightarrow$ 2-dimensional labeled table (collection of Series sharing the same index; multiple columns)

**Link: A DataFrame is essentially a dict-like container of aligned Series. Each column in a DataFrame is a Series**

# <u>Creating</u>

### Creating a Series

```python
pd.Series(data=None, index=None,dtype,name=None) 
# data receives list, tuple or numpy.ndarray 
# index takes a list or tuple of so called labels
# dtype stores one data type like "int", "float", "complex", "bool", "str" etc. and uses    upcasting to a common dtype

pd.Series({key1:val1, key2:val2, ...., keyn:valn}) 
# with key1,...,keyn collected in index and data=np.array([val1,val2,...,valn])

```

In [2]:
import pandas as pd

#help(pd.Series)

import numpy as np

In [44]:
# Create Series from list with labels A,B,C inside index object
s1 = pd.Series(data=[10, 20, 30],index=["A","B","C"],dtype="complex",name="s1")
print(s1,"\n")

# Create Series from numpy.ndarray with labels 1,2,3 inside index object
s2 = pd.Series(data=np.array(["Hi","there","!"]),index=[1,1,3],name="s2")
print(s2,"\n")

# Create Series from tuple with labels 10,20,30 inside index object
s3 = pd.Series(data=(3,2,1),index=[10,20,30],name="s3")
print(s3,"\n")

# Create Series from dicttionary with labels A,2,C inside index object
s4 = pd.Series({"A":10, 2:20, "C":30},dtype="float",name="s4")
print(s4,"\n")

A    10.0+ 0.0j
B    20.0+ 0.0j
C    30.0+ 0.0j
Name: s1, dtype: complex128

1       Hi
1    there
3        !
Name: s2, dtype: object

10    3
20    2
30    1
Name: s3, dtype: int64

A    10.0
2    20.0
C    30.0
Name: s4, dtype: float64

### Index and Values of a Series

```python
import pandas as pd
s = pd.Series(data,index,dtype,name)

# Get and reassign index object
s.index

# Reorder, add or remove index labels following new_labels of type list or tuple (does not change in place!)
s.reindex(new_labels)

# Rename index labels  using a dictionary or a function (does not change in place!)
s.rename(...)

# Turns index into a column and replaces index labels with default integers; also type of s.reset_index() is pandas.core.frame.DataFrame whereas type of s is pandas.core.series.Series
s.reset_index()

# Get data object (read only)
s.values

# Get and/or reassign name of series 
s.name


# Get and/or reassign index object name
s.index.name


```

In [ ]:
s5 = pd.Series(data=[[0],[1,2,3], "Hi"],index=[1,2,3],name="s5")
print(s5,"\n")
print("Index object of s5:", s5.index,"\n")
s5.index=["A","B","C"] # reassign index object of s5
print("New Index object of s5:", s5.index,"\n")
print("New s5:\n",s5,"\n")
print("Reordered labels of s5:\n",s5.reindex(("C","A","B")),"\n")
print("Add label \"D\" with default value of NaN to s5:\n",s5.reindex(("C","A","B","D")),"\n")
print("Remove label \"A\" from s5:\n",s5.reindex(("C","B","D")),"\n")
print("------------------------------------\n")

s6 = pd.Series(data=(3,2,1),index=[1,2,3],name="s6")
print("Data object of s6:", s6.values,"\n")
print("------------------------------------\n")

s7 = pd.Series(data=([0],(1,2,3), "Hi"),index=["Martha","Nick","Holly"],name="s7")
print(s7,"\n")
print("Name object of s7:", s7.name,"\n")
s7.name="Series" # reassign name object of s7
print("New name object of s7:", s7.name,"\n")
print("Rename old labels \"Martha\" and \"Nick\" of", s7.index,"to\n",s7.rename({"Martha":"Berta", "Nick":"Mike"}),"\n")
print("Rename all old labels of", s7.index,"to\n",s7.rename(lambda x: x.lower()),"\n")
print("------------------------------------\n")

s8 = pd.Series(data=(["patient1","patient1"],"patient2", "patient3"),index=["1st","2nd","3rd"],name="s8")
print(s8,"\n")
print("Name of index object of s8:", s8.index.name,"\n")
s8.index.name = "Labels" # assign a name to index object of s8
print("New name of index object of s8:", s8.index.name,"\n")
print("Reset index", s8.index,"of s8:\n",s8.reset_index(),"\n with type=",type(s8.reset_index()))

1          [0]
2    [1, 2, 3]
3           Hi
Name: s5, dtype: object

Index object of s5: Index([1, 2, 3], dtype='int64')

New Index object of s5: Index(['A', 'B', 'C'], dtype='object')

New s5:
 A          [0]
B    [1, 2, 3]
C           Hi
Name: s5, dtype: object

Reordered labels of s5:
 C           Hi
A          [0]
B    [1, 2, 3]
Name: s5, dtype: object

Add label "D" with default value of NaN to s5:
 C           Hi
A          [0]
B    [1, 2, 3]
D          NaN
Name: s5, dtype: object

Remove label "A" from s5:
 C           Hi
B    [1, 2, 3]
D          NaN
Name: s5, dtype: object

------------------------------------

Data object of s6: [3 2 1]

------------------------------------

Martha          [0]
Nick      (1, 2, 3)
Holly            Hi
Name: s7, dtype: object

Name object of s7: s7

New name object of s7: Series

Rename old labels "Martha" and "Nick" of Index(['Martha', 'Nick', 'Holly'], dtype='object') to
 Berta          [0]
Mike     (1, 2, 3)
Holly           Hi
Name: Series, dtype: object

Rename all old labels of Index(['Martha', 'Nick', 'Holly'], dtype='object') to
 martha          [0]
nick      (1, 2, 3)
holly            Hi
Name: Series, dtype: object

------------------------------------

1st    [patient1, patient1]
2nd                patient2
3rd                patient3
Name: s8, dtype: object

Name of index object of s8: None

New name of index object of s8: Labels

Reset index Index(['1st', '2nd', '3rd'], dtype='object', name='Labels') of s8:
   Labels                    s8
0    1st  [patient1, patient1]
1    2nd              patient2
2    3rd              patient3
 with type= <class 'pandas.core.frame.DataFrame'>

Labels
1st    [patient1, patient1]
2nd                patient2
3rd                patient3
Name: s8, dtype: object

### Useful Series attributes

```python
import pandas as pd

s = pd.Series(data,index,dtype,name)

# Returns data type of values in data
s.dtype

# Returns length of data
s.size

# Returns shape of data as tuple (s.size,) since Series are 1-dimensional
s.shape

# Returns a boolean Series indicating NaN values in data
s.isna()

# Replace NaN entries with some value inside val (does not change in place!)
s.fillna(val)

# Drop NaN entries and there corresponding index (does not change in place!)
s.dropna()

# Opposite of s.isna() (True where no NaN values)
s.notna()

```

In [134]:
s9 = pd.Series(data=(34,(34+0j),34.0),index=(0,1,2),name="s9")
print(s9,"\n")
print("dtype is",s9.dtype,"due to upcasting")
print("Size of s9 is",s9.size)
print("Shape of s9 is",s9.shape)
print("------------------------------------")

s10 = pd.Series(data=[None,2,None,4],index=("First", "Second","Third","Fourth"),name="s10")
print(s10,"\n")
print("dtype of s10 is by default", s10.dtype ,"because of Nonetype\n")
print("Identify non avilable numbers i.e. NaNs:\n",s10.isna(),"\n")
print("Identify available entries:\n",s10.notna(),"\n")
print("------------------------------------")

print("Copy of s10 with replaced NaN with \"Not Available\":\n",s10.fillna("Not Available"),"\n")
print("Copy of s10 with dropped NaN entries:\n",s10.dropna(),"\n")
print("s10 remains the same:\n",s10)

0    34.0+ 0.0j
1    34.0+ 0.0j
2    34.0+ 0.0j
Name: s9, dtype: complex128

dtype is complex128 due to upcasting
Size of s9 is 3
Shape of s9 is (3,)
------------------------------------
First     NaN
Second    2.0
Third     NaN
Fourth    4.0
Name: s10, dtype: float64

dtype of s10 is by default float64 because of Nonetype

Identify non avilable numbers i.e. NaNs:
 First      True
Second    False
Third      True
Fourth    False
Name: s10, dtype: bool

Identify available entries:
 First     False
Second     True
Third     False
Fourth     True
Name: s10, dtype: bool

------------------------------------
Copy of s10 with replaced NaN with "Not Available":
 First     Not Available
Second              2.0
Third     Not Available
Fourth              4.0
Name: s10, dtype: object

Copy of s10 with dropped NaN entries:
 Second    2.0
Fourth    4.0
Name: s10, dtype: float64

s10 remains the same:
 First     NaN
Second    2.0
Third     NaN
Fourth    4.0
Name: s10, dtype: float64

### Creating a Dataframe

```python
import pandas as pd

# Create using a dictionary (most common way)
df = pd.DataFrame(
    {
        'key1': [a,b,c,...,z], # column key1
        'key2': [a,b,c,...,z], # column key2
        ...
        'keyn': [a,b,c,...,z] # column keyn
    },
    index, # len(index) == len([a,b,c,...,z])
    dtype="..."
)
df
```
| index | key1 | key2 | ... | keyn |
| ----- | ---- | ---- | - | ---- |
| 0   | a    | a    | ... | a    |
| 1   | b    | b    | ... | b    |
| 2   | c    | c    | ... | c    |
|...     | ...    | ...    |... | ...    |
| 25   | z    | z    | ... | z    |


```python
# Create using a list of dictionaries
df = pd.Dataframe(
    [
        {"key1":a, "key2":a, ..., "keyn":a},
        {"key1":b, "key2":b, ..., "keyn":b},
        ...
        {"key1":z, "key2":z, ..., "keyn":z}
    ],
    index, # len(index) == number of dictionaries
    dtype="..."
)
df
```

| index | key1 | key2 | ... | keyn |
| ----- | ---- | ---- | - | ---- |
| 0   | a    | a    | ... | a    |
| 1   | b    | b    | ... | b    |
| 2   | c    | c    | ... | c    |
|...     | ...    | ...    |... | ...    |
| 25   | z    | z    | ... | z    |

```python


# Create using a list of lists / list of tuples / tuple of lists / tuple of tuples
df = pd.DataFrame(
    [
        [a1, a2, ..., an], # row 0
        [b1, b2, ..., bn], # row 1
        [c1, c2, ..., cn], # row 2
        ...
        [z1, z2, ..., zn] # row 25
    ],
    index, # len(index) == number of rows
    columns=["key1", "key2", ..., "keyn"],
    dtype="..."
)

df
```
| index | key1 | key2 | ... | keyn |
| ----- | ---- | ---- | - | ---- |
| 0   | a1    | a2    | ... | an    |
| 1   | b1    | b2    | ... | bn    |
| 2   | c1    | c2    | ... | cn    |
|...     | ...    | ...    |... | ...    |
| 25   | z1    | z2    | ... | zn    |


```python
# Create using a 2D numpy.ndarray
df = pd.DataFrame(
    np.array([
            [a1, a2, ..., an], # row 0
            [b1, b2, ..., bn], # row 1
            ...
            [z1, z2, ..., zn] # row 25
        ]), # or np.arange(num_row*num_col),reshape(num_row,num_col)
    index, # len(index) == number of rows
    columns=["key1", "key2", ..., "keyn"],
    dtype="..."
)
df
```
| index | key1 | key2 | ... | keyn |
| ----- | ---- | ---- | - | ---- |
| 0   | a1    | a2    | ... | an    |
| 1   | b1    | b2    | ... | bn    |
| 2   | c1    | c2    | ... | cn    |
|...     | ...    | ...    |... | ...    |
| 25   | z1    | z2    | ... | zn    |

In [93]:
df1 = pd.DataFrame(
    {
        'name': ["Jack", "Dan"], # colun name
        'age': [23, 25], # column age
        "city": ["London","Manchester"]
    }, 
    index=("Person1","Person2"),
    dtype="str"
)
print(df1,"\n")

df2 = pd.DataFrame([
    {"name":"Jack","age":23,"city":"London"},
    {"name":"Dan","age":25,"city":"Manchester"}
    ],
    index=["Person1","Person2"]
    )
print(df2,"\n")

df3 = pd.DataFrame([
        ["Jack",23,"London"],
        ["Dan",25,"Manchester"],
    ],
    columns=["name","age","city"],
    index=["Person1", "Person2"]
    )
print(df3,"\n")

df4 = pd.DataFrame(
    np.array([
        ["Jack", 23, "London"],
        ["Dan",25,"Manchester"]
    ]),
    columns=["name","age","city"],
    index=["Person1", "Person2"]
    )
df4

         name age        city
Person1  Jack  23      London
Person2   Dan  25  Manchester

         name  age        city
Person1  Jack   23      London
Person2   Dan   25  Manchester

         name  age        city
Person1  Jack   23      London
Person2   Dan   25  Manchester

         name age        city
Person1  Jack  23      London
Person2   Dan  25  Manchester

# <u>Reading</u>

| Action      | Code                                |
| ----------- | ----------------------------------- |
| read CSV (comma seperated values)   | `pd.read_csv(filepath,header,names,index_col,usecols,dtype,parse_dates,nrows,na_values,chunksize,na_filter,date_format,encoding)`           |
| read Excel  | `pd.read_excel(filepath,sheet_name,header,names,index_col,usecols,dtype,nrows,na_values,chunksize,na_filter,parse_dates)`        |
| read JSON | `pd.read_json(filepath)` |
| read SQL | `d.read_sql(query, connection)` |
| read Clipborad | `pd.read_clipboard()` |

```python
import pandas as pd
help(pd.read_csv)
help(pd.read_excel)
help(pd.read_json)
help(pd.read_clipboard)

```

In [106]:
filepath = "C:/Users/iyke/Documents/Data/winemag-data-130k-v2.csv"
df = pd.read_csv(filepath)
df.head() # first 5 rows of dataframe

,Unnamed: 0,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
0,0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia
1,1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos
2,2,US,"Tart and snappy, the flavors of lime flesh and...",NaN,87,14.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Rainstorm 2013 Pinot Gris (Willamette Valley),Pinot Gris,Rainstorm
3,3,US,"Pineapple rind, lemon pith and orange blossom ...",Reserve Late Harvest,87,13.0,Michigan,Lake Michigan Shore,NaN,Alexander Peartree,NaN,St. Julian 2013 Reserve Late Harvest Riesling ...,Riesling,St. Julian
4,4,US,"Much like the regular bottling from 2012, this...",Vintner's Reserve Wild Child Block,87,65.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Sweet Cheeks 2012 Vintner's Reserve Wild Child...,Pinot Noir,Sweet Cheeks

In [131]:
df = pd.read_csv(filepath,index_col="country") # use column country as row labels
df.head(3)

,Unnamed: 0,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
country,,,,,,,,,,,,,
Italy,0,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia
Portugal,1,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos
US,2,"Tart and snappy, the flavors of lime flesh and...",NaN,87,14.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Rainstorm 2013 Pinot Gris (Willamette Valley),Pinot Gris,Rainstorm

In [132]:
df = pd.read_csv(filepath,index_col=1) # use column country as row labels
df.head(3)

,Unnamed: 0,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
country,,,,,,,,,,,,,
Italy,0,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia
Portugal,1,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos
US,2,"Tart and snappy, the flavors of lime flesh and...",NaN,87,14.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Rainstorm 2013 Pinot Gris (Willamette Valley),Pinot Gris,Rainstorm

In [138]:
df = pd.read_csv(filepath,index_col=0) # use column Unnamed:0 as row labels and removes label
df.head(3)

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia
1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos
2,US,"Tart and snappy, the flavors of lime flesh and...",NaN,87,14.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Rainstorm 2013 Pinot Gris (Willamette Valley),Pinot Gris,Rainstorm

# <u>Writing</u>
| Action      | Code                                |
| ----------- | ----------------------------------- |
| write CSV   | `df.to_csv("out.csv", index=False,columns=[...], sep='...')` |
| write Excel | `df.to_excel("out.xlsx",index=False)`           |
| write JSON | `df.to_json('output.json', orient='records')` |
| write SQL |`df.to_sql('table_name', connection, if_exists='replace')` |


```python
with pd.ExcelWriter('file.xlsx') as writer:
    df.to_excel(writer, sheet_name='Sheet1') # Multiple sheets

```

In [139]:
df.head(20000).to_csv("winemag-data-20k-v2.csv") # write first 20k rows into new csv file in current directory

In [140]:
df = pd.read_csv("winemag-data-20k-v2.csv")
df.head()

,Unnamed: 0,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
0,0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia
1,1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos
2,2,US,"Tart and snappy, the flavors of lime flesh and...",NaN,87,14.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Rainstorm 2013 Pinot Gris (Willamette Valley),Pinot Gris,Rainstorm
3,3,US,"Pineapple rind, lemon pith and orange blossom ...",Reserve Late Harvest,87,13.0,Michigan,Lake Michigan Shore,NaN,Alexander Peartree,NaN,St. Julian 2013 Reserve Late Harvest Riesling ...,Riesling,St. Julian
4,4,US,"Much like the regular bottling from 2012, this...",Vintner's Reserve Wild Child Block,87,65.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Sweet Cheeks 2012 Vintner's Reserve Wild Child...,Pinot Noir,Sweet Cheeks