# Core Object of Pandas

DataFrame $\rightarrow$ 2-dimensional labeled table (collection of Series sharing the same index and having the column name as name of the Series)

| Series        | DataFrame              |
| ------------- | ---------------------- |
| 1-D           | 2-D                    |
| One column    | Multiple columns       |
| Has one index | Has row + column index |
| Used in Data Frames       | Columns of DataFrames are a Series

**A DataFrame is essentially a dict-like container of aligned Series. Each column in a DataFrame is a Series.**

# <u>Creating</u>

```python
import pandas as pd

# Create using a dictionary (most common way)
df = pd.DataFrame(
    data =  {
        'key0': [a,b,c,...,z], # column key0
        'key1': [a,b,c,...,z], # column key1
        ...
        'keyn': [a,b,c,...,z] # column keyn
            },
    index, # len(index) == len([a,b,c,...,z])
    dtype="..."
)
df
```
| index | key0 | key1 | ... | keyn |
| ----- | ---- | ---- | - | ---- |
| 0   | a    | a    | ... | a    |
| 1   | b    | b    | ... | b    |
| 2   | c    | c    | ... | c    |
|...     | ...    | ...    |... | ...    |
| 25   | z    | z    | ... | z    |


```python
# Create using a list of dictionaries
df = pd.Dataframe(
    data =  [
                {"key0":a, "key1":a, ..., "keyn":a},
                {"key0":b, "key1":b, ..., "keyn":b},
                ...
                {"key0":z, "key1":z, ..., "keyn":z}
            ],
    index, # len(index) == number of dictionaries
    dtype="..."
)
df
```

| index | key0 | key1 | ... | keyn |
| ----- | ---- | ---- | - | ---- |
| 0   | a    | a    | ... | a    |
| 1   | b    | b    | ... | b    |
| 2   | c    | c    | ... | c    |
|...     | ...    | ...    |... | ...    |
| 25   | z    | z    | ... | z    |

```python


# Create using a list of lists / list of tuples / tuple of lists / tuple of tuples
df = pd.DataFrame(
    data =  [
                [a1, a2, ..., an], # row 0
                [b1, b2, ..., bn], # row 1
                [c1, c2, ..., cn], # row 2
                ...
                [z1, z2, ..., zn] # row 25
            ],
    index, # len(index) == number of rows
    columns=["key0", "key2", ..., "keyn"],
    dtype="..."
)

df
```
| index | key0 | key1 | ... | keyn |
| ----- | ---- | ---- | - | ---- |
| 0   | a1    | a2    | ... | an    |
| 1   | b1    | b2    | ... | bn    |
| 2   | c1    | c2    | ... | cn    |
|...     | ...    | ...    |... | ...    |
| 25   | z1    | z2    | ... | zn    |


```python
# Create using a 2D numpy.ndarray
df = pd.DataFrame(
    data = np.array([
                        [a1, a2, ..., an], # row 0
                        [b1, b2, ..., bn], # row 1
                        ...
                        [z1, z2, ..., zn] # row 25
                    ]), # or np.arange(num_row*num_col),reshape(num_row,num_col)
    index, # len(index) == number of rows
    columns=["key0", "key1", ..., "keyn"],
    dtype="..."
)
df
```
| index | key0 | key1 | ... | keyn |
| ----- | ---- | ---- | - | ---- |
| 0   | a1    | a2    | ... | an    |
| 1   | b1    | b2    | ... | bn    |
| 2   | c1    | c2    | ... | cn    |
|...     | ...    | ...    |... | ...    |
| 25   | z1    | z2    | ... | zn    |


```python
# Create using zip()
column0 = [a1,...,z1]
...
columnk = [ak,...,zk]
df = pd.DataFrame(
        data=zip(column0,column1,...,columnk), # len(column0) == ... == len(columnk)
        index, # len(index) == len(column0)
        columns=["key0", "key1", ..., "keyk"],
        dtype="..."
    )

```

| index | key0 | key1 | ... | keyk |
| ----- | ---- | ---- | - | ---- |
| 0   | a1    | a2    | ... | ak    |
| 1   | b1    | b2    | ... | bk    |
| 2   | c1    | c2    | ... | ck    |
|...     | ...    | ...    |... | ...    |
| 25   | z1    | z2    | ... | zk    |

In [6]:
import pandas as pd

df1 = pd.DataFrame(
    {
        'name': ["Jack", "Dan"], # colun name
        'age': [23, 25], # column age
        "city": ["London","Manchester"]
    }, 
    index=("Person1","Person2"),
    dtype="str"
)
print(df1,"\n")

df2 = pd.DataFrame([
    {"name":"Jack","age":23,"city":"London"},
    {"name":"Dan","age":25,"city":"Manchester"}
    ],
    index=["Person1","Person2"]
    )
print(df2,"\n")

df3 = pd.DataFrame([
        ["Jack",23,"London"],
        ["Dan",25,"Manchester"],
    ],
    columns=["name","age","city"],
    index=["Person1", "Person2"]
    )
print(df3,"\n")

import numpy as np

df4 = pd.DataFrame(
    np.array([
        ["Jack", 23, "London"],
        ["Dan",25,"Manchester"]
    ]),
    columns=["name","age","city"],
    index=["Person1", "Person2"]
    )
print(df4)


col = ["Jack", "Dan"]
age=[23,25]
city=(50000, 60000, 70000)
df5 = pd.DataFrame(
    zip(["Jack", "Dan"],[23,25],["London","Manchester"]),
    columns=["name","age","city"],
    index=["Person1", "Person2"])
df5

         name age        city
Person1  Jack  23      London
Person2   Dan  25  Manchester

         name  age        city
Person1  Jack   23      London
Person2   Dan   25  Manchester

         name  age        city
Person1  Jack   23      London
Person2   Dan   25  Manchester

         name age        city
Person1  Jack  23      London
Person2   Dan  25  Manchester

         name  age        city
Person1  Jack   23      London
Person2   Dan   25  Manchester

### Inspecting and Exploring Dataframes

| Useful Functions        | What it does                 |
| --------------- | ---------------------------- |
| `df.head()`     | shows first 5 rows                 |
| `df.tail()`     | shows last 5 rows                  |
| `df.info()`     | shows column types + memory        |
| `df.describe()` | shows statistics (mean, std, etc.) |
| `df.shape`      | (num_rows, num_columns)              |
| `df.columns`    | displays column names                 |
| `df.dtypes`     | displays data types per column                   |
| `df.copy()`     | shallow copies df |
|  **Indexmanipulation**  | **What it does** |
| `df.index`      | displays row index labels                   |
| `df.index.name`  | stores the name of the index axis  |
| `df.rename_axis("...",axis="columns",inplace=True)`| Renames the index or columns axis label    |
| `df.reindex(index,labels,columns)`  | Conforms the DataFrame to a new set of index (or columns) labels. Can add, remove, or reorder rows/columns   |
| `df.set_index("id",in_place=True)` | Replaces index labels of df with values of column "id" |
| `df.reset_index(inplace=True)` | moves non-default index object into normal column and restores default index |

In [ ]:
df5 = pd.DataFrame(
    zip(["Jack", "Dan"],[23,25],["London","Manchester"]),
    columns=["name","age","city"],
    index=["Person1", "Person2"])
print(df5,"\n")
print("Description of df5:\n",df5.describe(),"\n")
print("Columns of df5:",df5.columns,"\n")
print("Index labels:",df5.index,"\n")
print("Data type per column:\n",df5.dtypes,"\n")
print("Set column \"name\" as index but leave original unchanged:\n",df5.set_index("name"),"\n")
df5.set_index("name",inplace=True) # Set column "name" as index and update original
print("New original DataFrame df5:\n",df5,"\n")
print("Restore column \"name\" and set default index but leave original unchanged:\n",df5.reset_index(),"\n")
df5.reset_index(inplace=True) # Restore column \"name\" and set default index and update original
print("New original DataFrame df5:\n",df5,"\n")

         name  age        city
Person1  Jack   23      London
Person2   Dan   25  Manchester

Description of df5:
              age
count   2.000000
mean   24.000000
std     1.414214
min    23.000000
25%    23.500000
50%    24.000000
75%    24.500000
max    25.000000

Columns of df5: Index(['name', 'age', 'city'], dtype='object')

Index labels: Index(['Person1', 'Person2'], dtype='object')

Data type per column:
 name    object
age      int64
city    object
dtype: object

Set column "name" as index but leave original unchanged:
       age        city
name
Jack   23      London
Dan    25  Manchester

New original DataFrame df5:
       age        city
name
Jack   23      London
Dan    25  Manchester

Restore column "name" and set default index but leave original unchanged:
    name  age        city
0  Jack   23      London
1   Dan   25  Manchester

New original DataFrame df5:
    name  age        city
0  Jack   23      London
1   Dan   25  Manchester

In [ ]:
df5 = pd.DataFrame(
    zip(["Jack", "Dan"],[23,25],["London","Manchester"]),
    columns=["name","age","city"],
    index=["Person1", "Person2"])
print(df5,"\n")
print("Index name of", df5.index,"of df5 is:",df5.index.name)
df5.index.name = "Personas" # change original to have index name "Personas"
print("Index name of", df5.index,"of df5 is:",df5.index.name)
print(df5,"\n")
print("Change index name not in place (original unchanged):\n",df5.rename_axis("row_id",axis="rows")) # same affect as df5.index.name = "row_id"
df5.rename_axis("row_id",inplace=True) # change original to have index name "row_id"
print(df5,"\n")
print("Column name of", df5.columns,"of df5 is:",df5.columns.name)
df5.rename_axis("features", axis="columns",inplace=True) # change column name in place
print("New original:\n",df5,"\n")
print("Column name of", df5.columns,"of df5 is:",df5.columns.name,"\n")
print("Reorder rows\n",df5.reindex(index=["Person2","Person1"]),"\n")
print("Reorder rows and add new row\n",df5.reindex(["Person2","Person1","Person3"]),"\n")
print("Remove a row\n",df5.reindex(["Person2"]),"\n")
print("Reorder columns, remove a column and add one\n",df5.reindex(columns=["city","age","job"]),"\n")

         name  age        city
Person1  Jack   23      London
Person2   Dan   25  Manchester

Index name of Index(['Person1', 'Person2'], dtype='object') of df5 is: None
Index name of Index(['Person1', 'Person2'], dtype='object', name='Personas') of df5 is: Personas
          name  age        city
Personas
Person1   Jack   23      London
Person2    Dan   25  Manchester

Change index name not in place (original unchanged):
          name  age        city
row_id
Person1  Jack   23      London
Person2   Dan   25  Manchester
         name  age        city
row_id
Person1  Jack   23      London
Person2   Dan   25  Manchester

Column name of Index(['name', 'age', 'city'], dtype='object') of df5 is: None
New original:
 features  name  age        city
row_id
Person1   Jack   23      London
Person2    Dan   25  Manchester

Column name of Index(['name', 'age', 'city'], dtype='object', name='features') of df5 is: features

Reorder rows
 features  name  age        city
row_id
Person2    Dan   25  Manchester
Person1   Jack   23      London

Reorder rows and add new row
 features  name   age        city
row_id
Person2    Dan  25.0  Manchester
Person1   Jack  23.0      London
Person3    NaN   NaN         NaN

Remove a row
 features name  age        city
row_id
Person2   Dan   25  Manchester

Reorder columns, remove a column and add one
 features        city  age  job
row_id
Person1       London   23  NaN
Person2   Manchester   25  NaN

In [ ]:
df6 = pd.DataFrame(
    {
        "Name":["Alice","Bob","Charlie"],
        "Age":[25,30,35],
        "Salary":(50000,60000,70000),
        "City":["Berlin","Paris","New York"],
    }
)

df6_shallow_copy = df6.copy() # Changing df6_shallow_copy does NOT change df6 and vice versa
print("Both Dataframes are the same:",all(df6_shallow_copy == df6))
print("Both variables point to same DataFrame in memory:",df6_shallow_copy is df6,"\n")
df6_shallow_copy["Age"] = "Twentyfive"
print(df6, "\n")
print(df6_shallow_copy, "\n")


df6_deep_copy = df6 # both variables point to the same DataFrame in memory and any change to df6_deep_copy will change df6 too
print("Both Dataframes are the same:",all(df6_deep_copy == df6))
print("Both variables point to same DataFrame in memory:",df6_deep_copy is df6,"\n")
df6_deep_copy["Age"] = "Twentythree"
print(df6, "\n")
print(df6_deep_copy, "\n")

Both Dataframes are the same: True
Both variables point to same DataFrame in memory: False

      Name  Age  Salary      City
0    Alice   25   50000    Berlin
1      Bob   30   60000     Paris
2  Charlie   35   70000  New York

      Name         Age  Salary      City
0    Alice  Twentyfive   50000    Berlin
1      Bob  Twentyfive   60000     Paris
2  Charlie  Twentyfive   70000  New York

Both Dataframes are the same: True
Both variables point to same DataFrame in memory: True

      Name          Age  Salary      City
0    Alice  Twentythree   50000    Berlin
1      Bob  Twentythree   60000     Paris
2  Charlie  Twentythree   70000  New York

      Name          Age  Salary      City
0    Alice  Twentythree   50000    Berlin
1      Bob  Twentythree   60000     Paris
2  Charlie  Twentythree   70000  New York

# <u>Reading</u>

| Action      | Code                                |
| ----------- | ----------------------------------- |
| read CSV (comma seperated values)   | `pd.read_csv(filepath,header,names,index_col,usecols,dtype,parse_dates,nrows,na_values,chunksize,na_filter,date_format,encoding)`           |
| read Excel  | `pd.read_excel(filepath,sheet_name,header,names,index_col,usecols,dtype,nrows,na_values,chunksize,na_filter,parse_dates)`        |
| read JSON | `pd.read_json(filepath)` |
| read SQL | `d.read_sql(query, connection)` |
| read Clipborad | `pd.read_clipboard()` |

```python
import pandas as pd
help(pd.read_csv)
help(pd.read_excel)
help(pd.read_json)
help(pd.read_clipboard)

```

In [ ]:
#filepath = "C:/Users/iyke/Documents/Data/winemag-data-130k-v2.csv"
filepath = "winemag-data-130k-v2.csv"
df7 = pd.read_csv(filepath)
df7.head() # first 5 rows of dataframe

,Unnamed: 0,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
0,0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia
1,1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos
2,2,US,"Tart and snappy, the flavors of lime flesh and...",NaN,87,14.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Rainstorm 2013 Pinot Gris (Willamette Valley),Pinot Gris,Rainstorm
3,3,US,"Pineapple rind, lemon pith and orange blossom ...",Reserve Late Harvest,87,13.0,Michigan,Lake Michigan Shore,NaN,Alexander Peartree,NaN,St. Julian 2013 Reserve Late Harvest Riesling ...,Riesling,St. Julian
4,4,US,"Much like the regular bottling from 2012, this...",Vintner's Reserve Wild Child Block,87,65.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Sweet Cheeks 2012 Vintner's Reserve Wild Child...,Pinot Noir,Sweet Cheeks

In [ ]:
df7 = pd.read_csv(filepath,index_col="country") # use column country as row labels
df7.head(3)

,Unnamed: 0,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
country,,,,,,,,,,,,,
Italy,0,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia
Portugal,1,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos
US,2,"Tart and snappy, the flavors of lime flesh and...",NaN,87,14.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Rainstorm 2013 Pinot Gris (Willamette Valley),Pinot Gris,Rainstorm

In [ ]:
df7 = pd.read_csv(filepath,index_col=1) # use column country as row labels
df7.head(3)

,Unnamed: 0,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
country,,,,,,,,,,,,,
Italy,0,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia
Portugal,1,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos
US,2,"Tart and snappy, the flavors of lime flesh and...",NaN,87,14.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Rainstorm 2013 Pinot Gris (Willamette Valley),Pinot Gris,Rainstorm

In [ ]:
df7 = pd.read_csv(filepath,index_col=0) # use column Unnamed:0 as row labels and removes label
df7.head(3)

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia
1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos
2,US,"Tart and snappy, the flavors of lime flesh and...",NaN,87,14.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Rainstorm 2013 Pinot Gris (Willamette Valley),Pinot Gris,Rainstorm

In [ ]:
print("Last 2 rows")
df7.tail(2)

Last 2 rows

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
129969,France,"A dry style of Pinot Gris, this is crisp with ...",NaN,90,32.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Marcel Deiss 2012 Pinot Gris (Alsace),Pinot Gris,Domaine Marcel Deiss
129970,France,"Big, rich and off-dry, this is powered by inte...",Lieu-dit Harth Cuvée Caroline,90,21.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Schoffit 2012 Lieu-dit Harth Cuvée Car...,Gewürztraminer,Domaine Schoffit

In [ ]:
print("Info on dataframe")
print(df7.info(),"\n")
# 13 columns of which only column points and price are of type integer or float
# therefor statistics only apply to these 2 columns
print("Shape of df in format (num_rows,num_cols):",df7.shape)
print("Statistics on dataframe\n",df7.describe())

Info on dataframe
<class 'pandas.core.frame.DataFrame'>
Index: 129971 entries, 0 to 129970
Data columns (total 13 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   country                129908 non-null  object
 1   description            129971 non-null  object
 2   designation            92506 non-null   object
 3   points                 129971 non-null  int64
 4   price                  120975 non-null  float64
 5   province               129908 non-null  object
 6   region_1               108724 non-null  object
 7   region_2               50511 non-null   object
 8   taster_name            103727 non-null  object
 9   taster_twitter_handle  98758 non-null   object
 10  title                  129971 non-null  object
 11  variety                129970 non-null  object
 12  winery                 129971 non-null  object
dtypes: float64(1), int64(1), object(11)
memory usage: 13.9+ MB
None

Shape of df in format (num_rows,num_cols): (129971, 13)
Statistics on dataframe
               points          price
count  129971.000000  120975.000000
mean       88.447138      35.363389
std         3.039730      41.022218
min        80.000000       4.000000
25%        86.000000      17.000000
50%        88.000000      25.000000
75%        91.000000      42.000000
max       100.000000    3300.000000

In [ ]:
print("Column names:\n",df7.columns,"\n")
print("Row index labels:\n",df7.index,"\n")
print("Data type inside each column:\n",df7.dtypes)

Column names:
 Index(['country', 'description', 'designation', 'points', 'price', 'province',
       'region_1', 'region_2', 'taster_name', 'taster_twitter_handle', 'title',
       'variety', 'winery'],
      dtype='object')

Row index labels:
 Index([     0,      1,      2,      3,      4,      5,      6,      7,      8,
            9,
       ...
       129961, 129962, 129963, 129964, 129965, 129966, 129967, 129968, 129969,
       129970],
      dtype='int64', length=129971)

Data type inside each column:
 country                   object
description               object
designation               object
points                     int64
price                    float64
province                  object
region_1                  object
region_2                  object
taster_name               object
taster_twitter_handle     object
title                     object
variety                   object
winery                    object
dtype: object

# <u>Writing</u>
| Action      | Code                                |
| ----------- | ----------------------------------- |
| write CSV   | `df.to_csv("out.csv", index=False,columns=[...], sep='...')` |
| write Excel | `df.to_excel("out.xlsx",index=False)`           |
| write JSON | `df.to_json('output.json', orient='records')` |
| write SQL |`df.to_sql('table_name', connection, if_exists='replace')` |


```python
with pd.ExcelWriter('file.xlsx') as writer:
    df.to_excel(writer, sheet_name='Sheet1') # Multiple sheets

```

In [ ]:
df8 = pd.DataFrame(
    {
        "Name":["Alice","Bob","Charlie"],
        "Age":[25,30,35],
        "Salary":(50000,60000,70000),
        "City":["Berlin","Paris","New York"],
        3:(1,False,"Yes")
    }
) 
print(df8,"\n")
print("Row index labels",df8.index)

df8.to_csv("output.csv", sep="|") # write dataframe into new csv file in current directory seperated by |

      Name  Age  Salary      City      3
0    Alice   25   50000    Berlin      1
1      Bob   30   60000     Paris  False
2  Charlie   35   70000  New York    Yes

Row index labels RangeIndex(start=0, stop=3, step=1)