# <u>Selecting</u>

```python
import pandas as pd
df = pd.DataFrame(data,index,columns)
```
### COLUMN SELECTION

```python
# Single column by column index
df[3] # -> returns a Series

# Single column by name
df['col'] # -> returns a Series
df.col # -> returns a Series and only if column name has no spaces/special charatcers

# Multiple columns by name list
df[['col1', 'col2',...,'colk']] # -> returns a DataFrame

```
**``.loc`` is label-based selection and when used with slicing the first element of the range is <u>included</u> as well as the last**

```python

# Multiple columns by name list
df.loc[:, ['col1', 'col2',...,'colk']] # -> returns a DataFrame

# Multiple columns by name (with Slicing -> col4 included)
df.loc[:, 'col1':'col4':step] # -> returns a DataFrame
```
**``.iloc`` is position-based selection and when used with slicing the first element of the range is <u>included</u> and the last <u>excluded</u>**

### ROW SELECTION

```python

# Single row by label
df.loc[label] # -> returns a Series

# Single row by label
df.loc[[label]] # -> returns a DataFrame

# Single row by integer position
df.iloc[3] # -> returns a Series

# n random rows
df.sample(n)

# Multiple rows by position
df[start:stop:step] # -> returns a DataFrame

# Multiple rows by label list
df.loc[[label1, label2]] # -> returns a DataFrame

# Multiple rows by position list
df.iloc[[0, 3, 5]] # -> returns a DataFrame

# Multiple rows by label slicing
df.loc[start:end:step] # -> returns a DataFrame

# Multiple rows by position slicing
df.iloc[2:5:1] # -> returns a DataFrame

```
**Both ``.loc`` and ``.iloc`` are row-first, column-second: ``.loc[row,column]`` and ``.iloc[row,column]``**

### COLUMN + ROW SELECTION
```python
# Single row + single column (label based)
df.loc[row_label, 'col'] # -> single entrie of dataframe

# Single row + single column (position based)
df.iloc[0, 4] # -> single entrie of dataframe

# Mulitple rows + multiple columns (label based)
df.loc[label1:label5, ['col1', 'col2', 'col3']]

# Mulitple rows + multiple columns (position based)
df.loc[1:5, 1:3]

# Fast single-value access
df.at[row_label2, col4] # label based
df.iat[2, 4] # position based

```

In [3]:
import pandas as pd
filepath = "winemag-data-130k-v2.csv"
reviews = pd.read_csv(filepath,index_col=0)
reviews.head(5)

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia
1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos
2,US,"Tart and snappy, the flavors of lime flesh and...",NaN,87,14.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Rainstorm 2013 Pinot Gris (Willamette Valley),Pinot Gris,Rainstorm
3,US,"Pineapple rind, lemon pith and orange blossom ...",Reserve Late Harvest,87,13.0,Michigan,Lake Michigan Shore,NaN,Alexander Peartree,NaN,St. Julian 2013 Reserve Late Harvest Riesling ...,Riesling,St. Julian
4,US,"Much like the regular bottling from 2012, this...",Vintner's Reserve Wild Child Block,87,65.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Sweet Cheeks 2012 Vintner's Reserve Wild Child...,Pinot Noir,Sweet Cheeks

In [99]:
reviews.sample(3) # 3 random draw of a row

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
1709,Italy,The packaging is totally crazy but the wine is...,Wine Obsession I Miti,86,65.0,Tuscany,Toscana,NaN,NaN,NaN,Villa Vignamaggio 2003 Wine Obsession I Miti R...,Red Blend,Villa Vignamaggio
108803,Italy,Bruna Grimaldi and her family present a delici...,Bricco Ambrogio,92,NaN,Piedmont,Barolo,NaN,NaN,NaN,Grimaldi Bruna 2008 Bricco Ambrogio (Barolo),Nebbiolo,Grimaldi Bruna
115767,US,"Soft in peach and orange-blossom, this wine of...",NaN,88,25.0,California,California,California Other,Virginie Boone,@vboone,Las Positas 2012 Muscat Canelli (California),Muscat Canelli,Las Positas

In [25]:
print("List of columns of Dataframe reviews:\n",reviews.columns,"\n")
print("Index labels of Dataframe reviwes:\n",reviews.index,"\n")

list(zip(list(range(len(reviews.columns))), reviews.columns))

List of columns of Dataframe reviews:
 Index(['country', 'description', 'designation', 'points', 'price', 'province',
       'region_1', 'region_2', 'taster_name', 'taster_twitter_handle', 'title',
       'variety', 'winery'],
      dtype='object')

Index labels of Dataframe reviwes:
 Index([     0,      1,      2,      3,      4,      5,      6,      7,      8,
            9,
       ...
       129961, 129962, 129963, 129964, 129965, 129966, 129967, 129968, 129969,
       129970],
      dtype='int64', length=129971)

[(0, 'country'),
 (1, 'description'),
 (2, 'designation'),
 (3, 'points'),
 (4, 'price'),
 (5, 'province'),
 (6, 'region_1'),
 (7, 'region_2'),
 (8, 'taster_name'),
 (9, 'taster_twitter_handle'),
 (10, 'title'),
 (11, 'variety'),
 (12, 'winery')]

In [ ]:
print("First 5 countries:\n",reviews.country.head(),"\n of type",type(reviews.country.head()),"\n")
print("First 5 provinces:\n",reviews["province"].head(),"\n of type",type(reviews["province"].head()),"\n")
print("First to third row of column \"taster_name\":\n",reviews["taster_name"][0:4],"\n")
print("Third row of column \"taster_name\":\n",reviews["taster_name"][2],"\n")

List of columns of Dataframe reviews:
 Index(['country', 'description', 'designation', 'points', 'price', 'province',
       'region_1', 'region_2', 'taster_name', 'taster_twitter_handle', 'title',
       'variety', 'winery'],
      dtype='object')

Index labels of Dataframe reviwes:
 Index([     0,      1,      2,      3,      4,      5,      6,      7,      8,
            9,
       ...
       129961, 129962, 129963, 129964, 129965, 129966, 129967, 129968, 129969,
       129970],
      dtype='int64', length=129971)

First 5 countries:
 0       Italy
1    Portugal
2          US
3          US
4          US
Name: country, dtype: object
 of type <class 'pandas.core.series.Series'>

First 5 provinces:
 0    Sicily & Sardinia
1                Douro
2               Oregon
3             Michigan
4               Oregon
Name: province, dtype: object
 of type <class 'pandas.core.series.Series'>

First to third row of column "taster_name":
 0         Kerin O’Keefe
1            Roger Voss
2          Paul Gregutt
3    Alexander Peartree
Name: taster_name, dtype: object

Third row of column "taster_name":
 Paul Gregutt

In [39]:
print(f"First row:\n{reviews.iloc[0]}\n")
print("First 5 countries:\n",reviews.iloc[:,0].head(),"\n of type",type(reviews.iloc[:,0].head()),"\n")
print("First 5 provinces:\n",reviews.iloc[0:5,5],"\n of type",type(reviews.iloc[0:4,5]),"\n")
print("First 3 titles:\n",reviews.iloc[[0,1,2],10],"\n of type",type(reviews.iloc[[0,1,2],10]),"\n")
print(f"Last 2 rows of columns \"country\" and \"points\":\n{reviews.tail(2)[["country","points"]]}\n")
print(f"Last 2 rows of columns \"country\" and \"points\":\n{reviews.iloc[-2:,[0,3]]}\n")

First row:
country                                                              Italy
description              Aromas include tropical fruit, broom, brimston...
designation                                                   Vulkà Bianco
points                                                                  87
price                                                                  NaN
province                                                 Sicily & Sardinia
region_1                                                              Etna
region_2                                                               NaN
taster_name                                                  Kerin O’Keefe
taster_twitter_handle                                         @kerinokeefe
title                                    Nicosia 2013 Vulkà Bianco  (Etna)
variety                                                        White Blend
winery                                                             Nicosia
Name: 0, dtype: object

First 5 countries:
 0       Italy
1    Portugal
2          US
3          US
4          US
Name: country, dtype: object
 of type <class 'pandas.core.series.Series'>

First 5 provinces:
 0    Sicily & Sardinia
1                Douro
2               Oregon
3             Michigan
4               Oregon
Name: province, dtype: object
 of type <class 'pandas.core.series.Series'>

First 3 titles:
 0                Nicosia 2013 Vulkà Bianco  (Etna)
1    Quinta dos Avidagos 2011 Avidagos Red (Douro)
2    Rainstorm 2013 Pinot Gris (Willamette Valley)
Name: title, dtype: object
 of type <class 'pandas.core.series.Series'>

Last 2 rows of columns "country" and "points":
       country  points
129969  France      90
129970  France      90

Last 2 rows of columns "country" and "points":
       country  points
129969  France      90
129970  France      90

In [54]:
print(f"Second Twitter Hanle: {reviews.loc[1,"taster_twitter_handle"]}")
print(f"Columns \"taster_name\", \"taster_twiiter_handle\" and \"points\"\n: {reviews.loc[:,["taster_twitter_handle", "taster_name","points"]]}")
print(f"Select two columns:\n{reviews[["price","points"]]}\n")

Second Twitter Hanle: @vossroger
Columns "taster_name", "taster_twiiter_handle" and "points"
:        taster_twitter_handle         taster_name  points
0               @kerinokeefe       Kerin O’Keefe      87
1                 @vossroger          Roger Voss      87
2                @paulgwine         Paul Gregutt      87
3                        NaN  Alexander Peartree      87
4                @paulgwine         Paul Gregutt      87
...                      ...                 ...     ...
129966                   NaN  Anna Lee C. Iijima      90
129967           @paulgwine         Paul Gregutt      90
129968            @vossroger          Roger Voss      90
129969            @vossroger          Roger Voss      90
129970            @vossroger          Roger Voss      90

[129971 rows x 3 columns]
Select two columns:
        price  points
0         NaN      87
1        15.0      87
2        14.0      87
3        13.0      87
4        65.0      87
...       ...     ...
129966   28.0      90
129967   75.0      90
129968   30.0      90
129969   32.0      90
129970   21.0      90

[129971 rows x 2 columns]

In [60]:
print("Index object of reviews Dataframe is:",reviews.index,"\n")
print("--------------------------------\n")
print(f"Select multiple rows by slcicing\n{reviews[0:5:2]}\n")
print("--------------------------------\n")
print(f"Select one row by slicing: \n{reviews[0:1]}\n of type {type(reviews[0:1])}\n")
print("--------------------------------\n")
print(f"Select one row by label: \n{reviews.loc[5]}\n of type {type(reviews.loc[5])}\n")
print("--------------------------------\n")
print(f"Select one row by label: \n{reviews.loc[[5]]}\n of type {type(reviews.loc[[5]])}\n")

Index object of reviews Dataframe is: Index([     0,      1,      2,      3,      4,      5,      6,      7,      8,
            9,
       ...
       129961, 129962, 129963, 129964, 129965, 129966, 129967, 129968, 129969,
       129970],
      dtype='int64', length=129971)

--------------------------------

Select multiple rows by slcicing
  country                                        description  \
0   Italy  Aromas include tropical fruit, broom, brimston...
2      US  Tart and snappy, the flavors of lime flesh and...
4      US  Much like the regular bottling from 2012, this...

                          designation  points  price           province  \
0                        Vulkà Bianco      87    NaN  Sicily & Sardinia
2                                 NaN      87   14.0             Oregon
4  Vintner's Reserve Wild Child Block      87   65.0             Oregon

            region_1           region_2    taster_name taster_twitter_handle  \
0               Etna                NaN  Kerin O’Keefe          @kerinokeefe
2  Willamette Valley  Willamette Valley   Paul Gregutt           @paulgwine
4  Willamette Valley  Willamette Valley   Paul Gregutt           @paulgwine

                                               title      variety  \
0                  Nicosia 2013 Vulkà Bianco  (Etna)  White Blend
2      Rainstorm 2013 Pinot Gris (Willamette Valley)   Pinot Gris
4  Sweet Cheeks 2012 Vintner's Reserve Wild Child...   Pinot Noir

         winery
0       Nicosia
2     Rainstorm
4  Sweet Cheeks

--------------------------------

Select one row by slicing:
  country                                        description   designation  \
0   Italy  Aromas include tropical fruit, broom, brimston...  Vulkà Bianco

   points  price           province region_1 region_2    taster_name  \
0      87    NaN  Sicily & Sardinia     Etna      NaN  Kerin O’Keefe

  taster_twitter_handle                              title      variety  \
0          @kerinokeefe  Nicosia 2013 Vulkà Bianco  (Etna)  White Blend

    winery
0  Nicosia
 of type <class 'pandas.core.frame.DataFrame'>

--------------------------------

Select one row by label:
country                                                              Spain
description              Blackberry and raspberry aromas show a typical...
designation                                                   Ars In Vitro
points                                                                  87
price                                                                 15.0
province                                                    Northern Spain
region_1                                                           Navarra
region_2                                                               NaN
taster_name                                              Michael Schachner
taster_twitter_handle                                          @wineschach
title                    Tandem 2011 Ars In Vitro Tempranillo-Merlot (N...
variety                                                 Tempranillo-Merlot
winery                                                              Tandem
Name: 5, dtype: object
 of type <class 'pandas.core.series.Series'>

--------------------------------

Select one row by label:
  country                                        description   designation  \
5   Spain  Blackberry and raspberry aromas show a typical...  Ars In Vitro

   points  price        province region_1 region_2        taster_name  \
5      87   15.0  Northern Spain  Navarra      NaN  Michael Schachner

  taster_twitter_handle                                              title  \
5           @wineschach  Tandem 2011 Ars In Vitro Tempranillo-Merlot (N...

              variety  winery
5  Tempranillo-Merlot  Tandem
 of type <class 'pandas.core.frame.DataFrame'>

In [59]:
print(f"Select value in (row, column): \n{reviews.loc[5, "price"]}\n")
print("--------------------------------\n")
print(f"Select one row by position: \n {reviews.iloc[5]}\n of type {type(reviews.iloc[5])}\n")
print("--------------------------------\n")
print(f"Value at (4, \"country\"): {reviews.at[4, "country"]}")

Select value in (row, column):
15.0

--------------------------------

Select one row by position:
 country                                                              Spain
description              Blackberry and raspberry aromas show a typical...
designation                                                   Ars In Vitro
points                                                                  87
price                                                                 15.0
province                                                    Northern Spain
region_1                                                           Navarra
region_2                                                               NaN
taster_name                                              Michael Schachner
taster_twitter_handle                                          @wineschach
title                    Tandem 2011 Ars In Vitro Tempranillo-Merlot (N...
variety                                                 Tempranillo-Merlot
winery                                                              Tandem
Name: 5, dtype: object
 of type <class 'pandas.core.series.Series'>

--------------------------------

Value at (4, "country"): US

In [62]:
import numpy as np
row, col = len(range(97, 107)), 5
m = np.arange(row*col).reshape(row,col)
df=pd.DataFrame(m, index=[chr(i) for i in range(97, 107)], columns=["A", "B", "C", "D", "E"])
print(df)
print(f"Select column: \n{df.loc[:, ["C"]]}")

    A   B   C   D   E
a   0   1   2   3   4
b   5   6   7   8   9
c  10  11  12  13  14
d  15  16  17  18  19
e  20  21  22  23  24
f  25  26  27  28  29
g  30  31  32  33  34
h  35  36  37  38  39
i  40  41  42  43  44
j  45  46  47  48  49
Select column:
    C
a   2
b   7
c  12
d  17
e  22
f  27
g  32
h  37
i  42
j  47

In [63]:
print(f"Select one row by slicing: \n{df[0:1]}\n")
print(f"Select multipl rows by slicing: \n{df[0:5:2]}\n")
print(f"Select one row by label: \n{df.loc["g"]}\n")
print(f"Select one row by label: \n{df.loc[["g"]]}\n")
print(f"Select (row, column): \n{df.loc["g", "A"]}\n")

Select one row by slicing:
   A  B  C  D  E
a  0  1  2  3  4

Select multipl rows by slicing:
    A   B   C   D   E
a   0   1   2   3   4
c  10  11  12  13  14
e  20  21  22  23  24

Select one row by label:
A    30
B    31
C    32
D    33
E    34
Name: g, dtype: int64

Select one row by label:
    A   B   C   D   E
g  30  31  32  33  34

Select (row, column):
30

In [64]:
print(f"Select subset: \n{df.loc[["g", "a"]]}\n")
print(f"Select subset: \n{df.loc[["g", "a"], ["A", "B"]]}\n")
print(f"Select one row by position: \n{df.iloc[6]}\n")
print(f"Select one row by position: \n{df.iloc[[6]]}\n")
print(f"Select (row, column) by position: \n{df.iloc[6, 3]}\n")
print(f"Select two rows and columns by position: \n{df.iloc[[1, 2], [3,4]]}\n")

Select subset:
    A   B   C   D   E
g  30  31  32  33  34
a   0   1   2   3   4

Select subset:
    A   B
g  30  31
a   0   1

Select one row by position:
A    30
B    31
C    32
D    33
E    34
Name: g, dtype: int64

Select one row by position:
    A   B   C   D   E
g  30  31  32  33  34

Select (row, column) by position:
33

Select two rows and columns by position:
    D   E
b   8   9
c  13  14

In [65]:
print(df)
print(f"Value at (row=\"c\", column=\"A\"): {df.at["c", "A"]}")
print(f"Value at (row=\"c\", column=\"A\"): {df.iat[2, 0]}")

    A   B   C   D   E
a   0   1   2   3   4
b   5   6   7   8   9
c  10  11  12  13  14
d  15  16  17  18  19
e  20  21  22  23  24
f  25  26  27  28  29
g  30  31  32  33  34
h  35  36  37  38  39
i  40  41  42  43  44
j  45  46  47  48  49
Value at (row="c", column="A"): 10
Value at (row="c", column="A"): 10

# <u>Filtering</u> (Boolean Indexing)

``&`` (and)

``|`` (or)

``~`` (not)

```python
import pandas as pd
df = pd.DataFrame(
    data =  {
        'key0': [a,b,c,...,z], # column key0
        'key1': [a,b,c,...,z], # column key1
        ...
        'keyn': [a,b,c,...,z] # column keyn
            },
    index, # len(index) == len([a,b,c,...,z])
    dtype="..."
)

# Select rows based on a condition
df[df["age"] > 20]
df[df["name"] == "Alice"]
df[(df["A"] > 0) & (df["B"] < 10)]


# Use .isin() to select rows with specific value inside a column
df[df['country'].isin(['USA', 'Canada'])]

# Select only rows fullfilling a specific condition inside a column
df[df["points"].between(85,90)]

# Return the elements in the given indices along an axis
df.take(indices,axis)

# Query Syntax: Human-readable selection using strings
df.query("age > 20")
df.query("city == 'Berlin'")
df.query("A > 5 and B < 10")
df.query('age > 30 and score > 80')


# Using .filter()
df.filter(like="name") # Columns containing substring
df.filter(regex="^A_") # Columns matching regex
# Selecting rows or columns by axis
df.filter(items=["col1", "col2"])
df.filter(items=["row3", "row5"], axis=0)


# Return the first n rows with the smallest values in columns in
# ascending order
df.nsmallest(n,columns)

# Return the first n rows with the largest values in columns in
# descending order
df.nlargest(n,columns)


```

In [91]:
print(f"Appearences of country \"Italy\" in column \"country\":\n {reviews.country=="Italy"}\n")
print(f"Select only rows with \"Italy\" as country:\n")
reviews.loc[reviews.country=="Italy"]

Appearences of country "Italy" in column "country":
 0          True
1         False
2         False
3         False
4         False
          ...
129966    False
129967    False
129968    False
129969    False
129970    False
Name: country, Length: 129971, dtype: bool

Select only rows with "Italy" as country:

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia
6,Italy,"Here's a bright, informal red that opens with ...",Belsito,87,16.0,Sicily & Sardinia,Vittoria,NaN,Kerin O’Keefe,@kerinokeefe,Terre di Giurfo 2013 Belsito Frappato (Vittoria),Frappato,Terre di Giurfo
13,Italy,This is dominated by oak and oak-driven aromas...,Rosso,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Masseria Setteporte 2012 Rosso (Etna),Nerello Mascalese,Masseria Setteporte
22,Italy,Delicate aromas recall white flower and citrus...,Ficiligno,87,19.0,Sicily & Sardinia,Sicilia,NaN,Kerin O’Keefe,@kerinokeefe,Baglio di Pianetto 2007 Ficiligno White (Sicilia),White Blend,Baglio di Pianetto
24,Italy,"Aromas of prune, blackcurrant, toast and oak c...",Aynat,87,35.0,Sicily & Sardinia,Sicilia,NaN,Kerin O’Keefe,@kerinokeefe,Canicattì 2009 Aynat Nero d'Avola (Sicilia),Nero d'Avola,Canicattì
...,...,...,...,...,...,...,...,...,...,...,...,...,...
129929,Italy,"This luminous sparkler has a sweet, fruit-forw...",NaN,91,38.0,Veneto,Prosecco Superiore di Cartizze,NaN,NaN,NaN,Col Vetoraz Spumanti NV Prosecco Superiore di...,Prosecco,Col Vetoraz Spumanti
129943,Italy,"A blend of Nero d'Avola and Syrah, this convey...",Adènzia,90,29.0,Sicily & Sardinia,Sicilia,NaN,Kerin O’Keefe,@kerinokeefe,Baglio del Cristo di Campobello 2012 Adènzia R...,Red Blend,Baglio del Cristo di Campobello
129947,Italy,"A blend of 65% Cabernet Sauvignon, 30% Merlot ...",Symposio,90,20.0,Sicily & Sardinia,Terre Siciliane,NaN,Kerin O’Keefe,@kerinokeefe,Feudo Principi di Butera 2012 Symposio Red (Te...,Red Blend,Feudo Principi di Butera
129961,Italy,"Intense aromas of wild cherry, baking spice, t...",NaN,90,30.0,Sicily & Sardinia,Sicilia,NaN,Kerin O’Keefe,@kerinokeefe,COS 2013 Frappato (Sicilia),Frappato,COS
129962,Italy,"Blackberry, cassis, grilled herb and toasted a...",Sàgana Tenuta San Giacomo,90,40.0,Sicily & Sardinia,Sicilia,NaN,Kerin O’Keefe,@kerinokeefe,Cusumano 2012 Sàgana Tenuta San Giacomo Nero d...,Nero d'Avola,Cusumano

In [96]:
print(f"Select rows with \"Italy\" as country and points greater than 90:\n")
reviews[(reviews.country=="Italy") & (reviews.points >= 90) ]

Select rows with "Italy" as country and points greater than 90:

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
120,Italy,"Slightly backward, particularly given the vint...",Bricco Rocche Prapó,92,70.0,Piedmont,Barolo,NaN,NaN,NaN,Ceretto 2003 Bricco Rocche Prapó (Barolo),Nebbiolo,Ceretto
130,Italy,"At the first it was quite muted and subdued, b...",Bricco Rocche Brunate,91,70.0,Piedmont,Barolo,NaN,NaN,NaN,Ceretto 2003 Bricco Rocche Brunate (Barolo),Nebbiolo,Ceretto
133,Italy,"Einaudi's wines have been improving lately, an...",NaN,91,68.0,Piedmont,Barolo,NaN,NaN,NaN,Poderi Luigi Einaudi 2003 Barolo,Nebbiolo,Poderi Luigi Einaudi
135,Italy,The color is just beginning to show signs of b...,Sorano,91,60.0,Piedmont,Barolo,NaN,NaN,NaN,Giacomo Ascheri 2001 Sorano (Barolo),Nebbiolo,Giacomo Ascheri
140,Italy,"A big, fat, luscious wine with plenty of toast...",Costa Bruna,90,26.0,Piedmont,Barbera d'Alba,NaN,NaN,NaN,Poderi Colla 2005 Costa Bruna (Barbera d'Alba),Barbera,Poderi Colla
...,...,...,...,...,...,...,...,...,...,...,...,...,...
129929,Italy,"This luminous sparkler has a sweet, fruit-forw...",NaN,91,38.0,Veneto,Prosecco Superiore di Cartizze,NaN,NaN,NaN,Col Vetoraz Spumanti NV Prosecco Superiore di...,Prosecco,Col Vetoraz Spumanti
129943,Italy,"A blend of Nero d'Avola and Syrah, this convey...",Adènzia,90,29.0,Sicily & Sardinia,Sicilia,NaN,Kerin O’Keefe,@kerinokeefe,Baglio del Cristo di Campobello 2012 Adènzia R...,Red Blend,Baglio del Cristo di Campobello
129947,Italy,"A blend of 65% Cabernet Sauvignon, 30% Merlot ...",Symposio,90,20.0,Sicily & Sardinia,Terre Siciliane,NaN,Kerin O’Keefe,@kerinokeefe,Feudo Principi di Butera 2012 Symposio Red (Te...,Red Blend,Feudo Principi di Butera
129961,Italy,"Intense aromas of wild cherry, baking spice, t...",NaN,90,30.0,Sicily & Sardinia,Sicilia,NaN,Kerin O’Keefe,@kerinokeefe,COS 2013 Frappato (Sicilia),Frappato,COS
129962,Italy,"Blackberry, cassis, grilled herb and toasted a...",Sàgana Tenuta San Giacomo,90,40.0,Sicily & Sardinia,Sicilia,NaN,Kerin O’Keefe,@kerinokeefe,Cusumano 2012 Sàgana Tenuta San Giacomo Nero d...,Nero d'Avola,Cusumano

In [98]:
print(f"Select rows with \"Italy\" as country or points greater than 90:\n")
reviews[(reviews["country"]=="Italy") | (reviews["points"] >= 90) ]

Select rows with "Italy" as country or points greater than 90:

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia
6,Italy,"Here's a bright, informal red that opens with ...",Belsito,87,16.0,Sicily & Sardinia,Vittoria,NaN,Kerin O’Keefe,@kerinokeefe,Terre di Giurfo 2013 Belsito Frappato (Vittoria),Frappato,Terre di Giurfo
13,Italy,This is dominated by oak and oak-driven aromas...,Rosso,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Masseria Setteporte 2012 Rosso (Etna),Nerello Mascalese,Masseria Setteporte
22,Italy,Delicate aromas recall white flower and citrus...,Ficiligno,87,19.0,Sicily & Sardinia,Sicilia,NaN,Kerin O’Keefe,@kerinokeefe,Baglio di Pianetto 2007 Ficiligno White (Sicilia),White Blend,Baglio di Pianetto
24,Italy,"Aromas of prune, blackcurrant, toast and oak c...",Aynat,87,35.0,Sicily & Sardinia,Sicilia,NaN,Kerin O’Keefe,@kerinokeefe,Canicattì 2009 Aynat Nero d'Avola (Sicilia),Nero d'Avola,Canicattì
...,...,...,...,...,...,...,...,...,...,...,...,...,...
129966,Germany,Notes of honeysuckle and cantaloupe sweeten th...,Brauneberger Juffer-Sonnenuhr Spätlese,90,28.0,Mosel,NaN,NaN,Anna Lee C. Iijima,NaN,Dr. H. Thanisch (Erben Müller-Burggraef) 2013 ...,Riesling,Dr. H. Thanisch (Erben Müller-Burggraef)
129967,US,Citation is given as much as a decade of bottl...,NaN,90,75.0,Oregon,Oregon,Oregon Other,Paul Gregutt,@paulgwine,Citation 2004 Pinot Noir (Oregon),Pinot Noir,Citation
129968,France,Well-drained gravel soil gives this wine its c...,Kritt,90,30.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Gresser 2013 Kritt Gewurztraminer (Als...,Gewürztraminer,Domaine Gresser
129969,France,"A dry style of Pinot Gris, this is crisp with ...",NaN,90,32.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Marcel Deiss 2012 Pinot Gris (Alsace),Pinot Gris,Domaine Marcel Deiss
129970,France,"Big, rich and off-dry, this is powered by inte...",Lieu-dit Harth Cuvée Caroline,90,21.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Schoffit 2012 Lieu-dit Harth Cuvée Car...,Gewürztraminer,Domaine Schoffit

In [100]:
print(f"Select only rows with \"Italy\" or \"France\" as country:")
reviews[reviews["country"].isin(["Italy","France"])]

Select only rows with "Italy" or "France" as country:

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia
6,Italy,"Here's a bright, informal red that opens with ...",Belsito,87,16.0,Sicily & Sardinia,Vittoria,NaN,Kerin O’Keefe,@kerinokeefe,Terre di Giurfo 2013 Belsito Frappato (Vittoria),Frappato,Terre di Giurfo
7,France,This dry and restrained wine offers spice in p...,NaN,87,24.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Trimbach 2012 Gewurztraminer (Alsace),Gewürztraminer,Trimbach
9,France,This has great depth of flavor with its fresh ...,Les Natures,87,27.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Jean-Baptiste Adam 2012 Les Natures Pinot Gris...,Pinot Gris,Jean-Baptiste Adam
11,France,"This is a dry wine, very spicy, with a tight, ...",NaN,87,30.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Leon Beyer 2012 Gewurztraminer (Alsace),Gewürztraminer,Leon Beyer
...,...,...,...,...,...,...,...,...,...,...,...,...,...
129964,France,"Initially quite muted, this wine slowly develo...",Domaine Saint-Rémy Herrenweg,90,NaN,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Ehrhart 2013 Domaine Saint-Rémy Herren...,Gewürztraminer,Domaine Ehrhart
129965,France,"While it's rich, this beautiful dry wine also ...",Seppi Landmann Vallée Noble,90,28.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Rieflé-Landmann 2013 Seppi Landmann Va...,Pinot Gris,Domaine Rieflé-Landmann
129968,France,Well-drained gravel soil gives this wine its c...,Kritt,90,30.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Gresser 2013 Kritt Gewurztraminer (Als...,Gewürztraminer,Domaine Gresser
129969,France,"A dry style of Pinot Gris, this is crisp with ...",NaN,90,32.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Marcel Deiss 2012 Pinot Gris (Alsace),Pinot Gris,Domaine Marcel Deiss
129970,France,"Big, rich and off-dry, this is powered by inte...",Lieu-dit Harth Cuvée Caroline,90,21.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Schoffit 2012 Lieu-dit Harth Cuvée Car...,Gewürztraminer,Domaine Schoffit

In [108]:
print(f"Select rows with points greater than 30 and only look at prices:\n{reviews.loc[reviews['points'] > 30, 'price']}\n")
print(f"Select only rows with points between 85 and 90:")
reviews[reviews["points"].between(85,90)]

Select rows with points greater than 30 and only look at prices:
0          NaN
1         15.0
2         14.0
3         13.0
4         65.0
          ...
129966    28.0
129967    75.0
129968    30.0
129969    32.0
129970    21.0
Name: price, Length: 129971, dtype: float64

Select only rows with points between 85 and 90:

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia
1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos
2,US,"Tart and snappy, the flavors of lime flesh and...",NaN,87,14.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Rainstorm 2013 Pinot Gris (Willamette Valley),Pinot Gris,Rainstorm
3,US,"Pineapple rind, lemon pith and orange blossom ...",Reserve Late Harvest,87,13.0,Michigan,Lake Michigan Shore,NaN,Alexander Peartree,NaN,St. Julian 2013 Reserve Late Harvest Riesling ...,Riesling,St. Julian
4,US,"Much like the regular bottling from 2012, this...",Vintner's Reserve Wild Child Block,87,65.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Sweet Cheeks 2012 Vintner's Reserve Wild Child...,Pinot Noir,Sweet Cheeks
...,...,...,...,...,...,...,...,...,...,...,...,...,...
129966,Germany,Notes of honeysuckle and cantaloupe sweeten th...,Brauneberger Juffer-Sonnenuhr Spätlese,90,28.0,Mosel,NaN,NaN,Anna Lee C. Iijima,NaN,Dr. H. Thanisch (Erben Müller-Burggraef) 2013 ...,Riesling,Dr. H. Thanisch (Erben Müller-Burggraef)
129967,US,Citation is given as much as a decade of bottl...,NaN,90,75.0,Oregon,Oregon,Oregon Other,Paul Gregutt,@paulgwine,Citation 2004 Pinot Noir (Oregon),Pinot Noir,Citation
129968,France,Well-drained gravel soil gives this wine its c...,Kritt,90,30.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Gresser 2013 Kritt Gewurztraminer (Als...,Gewürztraminer,Domaine Gresser
129969,France,"A dry style of Pinot Gris, this is crisp with ...",NaN,90,32.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Marcel Deiss 2012 Pinot Gris (Alsace),Pinot Gris,Domaine Marcel Deiss
129970,France,"Big, rich and off-dry, this is powered by inte...",Lieu-dit Harth Cuvée Caroline,90,21.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Schoffit 2012 Lieu-dit Harth Cuvée Car...,Gewürztraminer,Domaine Schoffit

In [116]:
print("Take rows 10 and 1:")
reviews.take([10,1],axis=0)

Take rows 10 and 1:

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
10,US,"Soft, supple plum envelopes an oaky structure ...",Mountain Cuvée,87,19.0,California,Napa Valley,Napa,Virginie Boone,@vboone,Kirkland Signature 2011 Mountain Cuvée Caberne...,Cabernet Sauvignon,Kirkland Signature
1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos

In [118]:
print("Take last row and the one before last:")
reviews.take([-1,-2])

Take last row and the one before last:

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
129970,France,"Big, rich and off-dry, this is powered by inte...",Lieu-dit Harth Cuvée Caroline,90,21.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Schoffit 2012 Lieu-dit Harth Cuvée Car...,Gewürztraminer,Domaine Schoffit
129969,France,"A dry style of Pinot Gris, this is crisp with ...",NaN,90,32.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Marcel Deiss 2012 Pinot Gris (Alsace),Pinot Gris,Domaine Marcel Deiss

In [117]:
print("Take columns 10 and 1:")
reviews.take([10,1],axis=1)

Take columns 10 and 1:

,title,description
0,Nicosia 2013 Vulkà Bianco (Etna),"Aromas include tropical fruit, broom, brimston..."
1,Quinta dos Avidagos 2011 Avidagos Red (Douro),"This is ripe and fruity, a wine that is smooth..."
2,Rainstorm 2013 Pinot Gris (Willamette Valley),"Tart and snappy, the flavors of lime flesh and..."
3,St. Julian 2013 Reserve Late Harvest Riesling ...,"Pineapple rind, lemon pith and orange blossom ..."
4,Sweet Cheeks 2012 Vintner's Reserve Wild Child...,"Much like the regular bottling from 2012, this..."
...,...,...
129966,Dr. H. Thanisch (Erben Müller-Burggraef) 2013 ...,Notes of honeysuckle and cantaloupe sweeten th...
129967,Citation 2004 Pinot Noir (Oregon),Citation is given as much as a decade of bottl...
129968,Domaine Gresser 2013 Kritt Gewurztraminer (Als...,Well-drained gravel soil gives this wine its c...
129969,Domaine Marcel Deiss 2012 Pinot Gris (Alsace),"A dry style of Pinot Gris, this is crisp with ..."
129970,Domaine Schoffit 2012 Lieu-dit Harth Cuvée Car...,"Big, rich and off-dry, this is powered by inte..."

In [ ]:
print("5 largest values in row \"price\" in descending order:")
reviews.nlargest(5, 'price')

5 largest values in row "price":

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
80290,France,This ripe wine shows plenty of blackberry frui...,NaN,88,3300.0,Bordeaux,Médoc,NaN,Roger Voss,@vossroger,Château les Ormes Sorbet 2013 Médoc,Bordeaux-style Red Blend,Château les Ormes Sorbet
15840,France,The wine is a velvet glove in an iron fist. Th...,NaN,96,2500.0,Bordeaux,Pomerol,NaN,Roger Voss,@vossroger,Château Pétrus 2014 Pomerol,Bordeaux-style Red Blend,Château Pétrus
98380,France,"A superb wine from a great year, this is power...",NaN,96,2500.0,Burgundy,La Romanée,NaN,Roger Voss,@vossroger,Domaine du Comte Liger-Belair 2010 La Romanée,Pinot Noir,Domaine du Comte Liger-Belair
120391,US,The nose on this single-vineyard wine from a s...,Roger Rose Vineyard,91,2013.0,California,Arroyo Seco,Central Coast,Matt Kettmann,@mattkettmann,Blair 2013 Roger Rose Vineyard Chardonnay (Arr...,Chardonnay,Blair
65352,France,This extravagantly perfumed wine has great jui...,NaN,97,2000.0,Bordeaux,Pomerol,NaN,Roger Voss,@vossroger,Château Pétrus 2011 Pomerol,Bordeaux-style Red Blend,Château Pétrus

In [ ]:
print("15 smallest values in row \"price\" in ascending order:")
reviews.nsmallest(15, 'price')

5 smallest values in row "price" in ascending order:

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
1987,Spain,Berry and cherry aromas are surprisingly sturd...,Flirty Bird,85,4.0,Central Spain,Vino de la Tierra de Castilla,NaN,Michael Schachner,@wineschach,Felix Solis 2013 Flirty Bird Syrah (Vino de la...,Syrah,Felix Solis
20484,US,"Fruity, soft and rather sweet, this wine smell...",NaN,85,4.0,California,Clarksburg,Central Valley,Jim Gordon,@gordone_cellars,Dancing Coyote 2015 White (Clarksburg),White Blend,Dancing Coyote
29553,Argentina,"Crimson in color but also translucent, with a ...",Red,84,4.0,Mendoza Province,Mendoza,NaN,Michael Schachner,@wineschach,Broke Ass 2009 Red Malbec-Syrah (Mendoza),Malbec-Syrah,Broke Ass
31530,US,"Packaged in a cute yellow recyclable Tetrapak,...",NaN,84,4.0,California,California,California Other,NaN,NaN,Bandit NV Chardonnay (California),Chardonnay,Bandit
59507,US,"Sweet and fruity, this canned wine feels soft ...",Unoaked,83,4.0,California,California,California Other,Jim Gordon,@gordone_cellars,Pam's Cuties NV Unoaked Chardonnay (California),Chardonnay,Pam's Cuties
61768,Spain,This opens with standard cherry and berry arom...,NaN,84,4.0,Levante,Yecla,NaN,Michael Schachner,@wineschach,Terrenal 2010 Cabernet Sauvignon (Yecla),Cabernet Sauvignon,Terrenal
64590,US,"There's a lot going on in this Merlot, which i...",NaN,86,4.0,California,California,California Other,NaN,NaN,Bandit NV Merlot (California),Merlot,Bandit
110255,US,"A good everyday Merlot, dry and rich in tannin...",NaN,84,4.0,California,California,California Other,NaN,NaN,Bandit NV Merlot (California),Merlot,Bandit
112919,Spain,"Nice on the nose, this has a leafy note and a ...",Estate Bottled,84,4.0,Levante,Yecla,NaN,Michael Schachner,@wineschach,Terrenal 2010 Estate Bottled Tempranillo (Yecla),Tempranillo,Terrenal
117303,Spain,"Tropical fruit and citrus aromas aren't bad, b...",Flirty Bird,82,4.0,Central Spain,Vino de la Tierra de Castilla,NaN,Michael Schachner,@wineschach,Felix Solis 2012 Flirty Bird White (Vino de la...,White Blend,Felix Solis
126096,Romania,Notes of sun-dried hay and green flower highli...,UnWineD,86,4.0,Viile Timisului,NaN,NaN,Anna Lee C. Iijima,NaN,Cramele Recas 2011 UnWineD Pinot Grigio (Viile...,Pinot Grigio,Cramele Recas
2780,Portugal,"This feels very ripe, perhaps overripe, with i...",Morgado da Canita,84,5.0,Alentejano,NaN,NaN,Roger Voss,@vossroger,Herdade dos Machados 2009 Morgado da Canita Re...,Portuguese Red,Herdade dos Machados
3167,Italy,"Packaged in a pocket-friendly 187-ml bottle, t...",Mini,86,5.0,Veneto,Prosecco,NaN,NaN,NaN,Anna Spinato NV Mini (Prosecco),Glera,Anna Spinato
3950,Portugal,"On the dry side, with caramel and strawberry f...",Escolha,83,5.0,Vinho Verde,NaN,NaN,Roger Voss,@vossroger,Adega Cooperativa Ponte de Barca 2010 Escolha ...,Rosé,Adega Cooperativa Ponte de Barca
5789,France,"This is a jammy and fruit-forward selection, w...",NaN,83,5.0,France Other,Vin de France,NaN,Lauren Buzzeo,@laurbuzz,Belle Made For You NV Cabernet Sauvignon (Vin ...,Cabernet Sauvignon,Belle Made For You