# <u>Grouping</u>

```python
# Split data by single column
df.groupby(by="city") # returns GroupBy object but does nothing yet

# Split data by multiple columns
df.groupby(by=['department', 'gender']) # Creates hierarchical groups

# Group by index
df.groupby(level=0)

# Single aggregation after grouping
df.groupby('department')['salary'].mean()

# Multiple aggregations after grouping
df.groupby('department')['salary'].agg(['mean', 'max', 'min'])

# Multiindex
df.groupby(by=['department', 'gender']).description.agg([len])

# Different agg per column
df.groupby("city").agg({
    "age": ["mean", "max"],
    "salary": "sum"
})

# Named aggregations
df.groupby('department').agg(
    avg_salary=('salary', 'mean'),
    max_age=('age', 'max')
)

# Group filtering
df.groupby('dept').filter(lambda g: len(g) > 5)

# Common groupby operations
df.groupby('dept').size()
df.groupby('dept').count()
df.groupby('dept')['col'].nunique()

```

In [8]:
import pandas as pd
reviews = pd.read_csv("winemag-data-130k-v2.csv",index_col=0)

In [ ]:
reviews.groupby(by="points")["points"] # does nothing yet

In [14]:
print(f"Count occurences of points:\n{reviews.groupby(by="points")["points"].count()}\n")
print(f"Count occurences of points:\n{reviews["points"].value_counts()}\n")

Count occurences of points:
points
80       397
81       692
82      1836
83      3025
84      6480
85      9530
86     12600
87     16933
88     17207
89     12226
90     15410
91     11359
92      9613
93      6489
94      3758
95      1535
96       523
97       229
98        77
99        33
100       19
Name: points, dtype: int64

Count occurences of points:
points
88     17207
87     16933
90     15410
86     12600
89     12226
91     11359
92      9613
85      9530
93      6489
84      6480
94      3758
83      3025
82      1836
95      1535
81       692
96       523
80       397
97       229
98        77
99        33
100       19
Name: count, dtype: int64

In [16]:
print(f"Get cheapest wine in each point value category:\n{reviews.groupby("points").price.min()}")

Get cheapest wine in each point value category:
points
80      5.0
81      5.0
82      4.0
83      4.0
84      4.0
85      4.0
86      4.0
87      5.0
88      6.0
89      7.0
90      8.0
91      7.0
92     11.0
93     12.0
94     13.0
95     20.0
96     20.0
97     35.0
98     50.0
99     44.0
100    80.0
Name: price, dtype: float64

In [33]:
print(f"Select name of the first wine reviewed from each winery:\n{reviews.groupby("winery").apply(lambda df: df.title.iloc[0],include_groups=False)}")

Select name of the first wine reviewed from each winery:
winery
1+1=3                                     1+1=3 NV Rosé Sparkling (Cava)
10 Knots                            10 Knots 2010 Viognier (Paso Robles)
100 Percent Wine              100 Percent Wine 2015 Moscato (California)
1000 Stories           1000 Stories 2013 Bourbon Barrel Aged Zinfande...
1070 Green                  1070 Green 2011 Sauvignon Blanc (Rutherford)
                                             ...
Órale                       Órale 2011 Cabronita Red (Santa Ynez Valley)
Öko                    Öko 2013 Made With Organically Grown Grapes Ma...
Ökonomierat Rebholz    Ökonomierat Rebholz 2007 Von Rotliegenden Spät...
àMaurice               àMaurice 2013 Fred Estate Syrah (Walla Walla V...
Štoka                                    Štoka 2009 Izbrani Teran (Kras)
Length: 16757, dtype: object

In [36]:
print(f"Pick best wine by country and province:\n")
reviews.groupby(["country","province"]).apply(lambda df:df.loc[df.points.idxmax()],include_groups=False)

Pick best wine by country and province:

                                                                  description  \
country   province
Argentina Mendoza Province  If the color doesn't tell the full story, the ...
          Other             Take note, this could be the best wine Colomé ...
Armenia   Armenia           Deep salmon in color, this wine offers a bouqu...
Australia Australia Other   Writes the book on how to make a wine filled w...
          New South Wales   De Bortoli's Noble One is as good as ever in 2...
...                                                                       ...
Uruguay   Juanico           This mature Bordeaux-style blend is earthy on ...
          Montevideo        A rich, heady bouquet offers aromas of blackbe...
          Progreso          Rusty in color but deep and complex in nature,...
          San Jose          Baked, sweet, heavy aromas turn earthy with ti...
          Uruguay           Cherry and berry aromas are ripe, healthy and ...

                                                        designation  points  \
country   province
Argentina Mendoza Province                         Nicasia Vineyard      97
          Other                                             Reserva      95
Armenia   Armenia                                    Estate Bottled      88
Australia Australia Other                             Sarah's Blend      93
          New South Wales                        Noble One Bortytis      94
...                                                             ...     ...
Uruguay   Juanico                  Preludio Barrel Select Lote N 77      90
          Montevideo        Monte Vide Eu Tannat-Merlot-Tempranillo      91
          Progreso                   Etxe Oneko Fortified Sweet Red      90
          San Jose                         El Preciado Gran Reserva      87
          Uruguay                         Blend 002 Limited Edition      91

                            price                 region_1 region_2  \
country   province
Argentina Mendoza Province  120.0                  Mendoza      NaN
          Other              90.0                    Salta      NaN
Armenia   Armenia            15.0                      NaN      NaN
Australia Australia Other    15.0  South Eastern Australia      NaN
          New South Wales    32.0          New South Wales      NaN
...                           ...                      ...      ...
Uruguay   Juanico            45.0                      NaN      NaN
          Montevideo         60.0                      NaN      NaN
          Progreso           46.0                      NaN      NaN
          San Jose           50.0                      NaN      NaN
          Uruguay            22.0                      NaN      NaN

                                  taster_name taster_twitter_handle  \
country   province
Argentina Mendoza Province  Michael Schachner           @wineschach
          Other             Michael Schachner           @wineschach
Armenia   Armenia               Mike DeSimone        @worldwineguys
Australia Australia Other                 NaN                   NaN
          New South Wales      Joe Czerwinski                @JoeCz
...                                       ...                   ...
Uruguay   Juanico           Michael Schachner           @wineschach
          Montevideo        Michael Schachner           @wineschach
          Progreso          Michael Schachner           @wineschach
          San Jose          Michael Schachner           @wineschach
          Uruguay           Michael Schachner           @wineschach

                                                                        title  \
country   province
Argentina Mendoza Province  Bodega Catena Zapata 2006 Nicasia Vineyard Mal...
          Other                            Colomé 2010 Reserva Malbec (Salta)
Armenia   Armenia                 Van Ardi 2015 Estate Bottled Rosé (Armenia)
Australia Australia Other   Marquis Philips 2000 Sarah's Blend Red (South ...
          New South Wales   De Bortoli 2007 Noble One Bortytis Semillon (N...
...                                                                       ...
Uruguay   Juanico           Familia Deicas 2004 Preludio Barrel Select Lot...
          Montevideo        Bouza 2015 Monte Vide Eu Tannat-Merlot-Tempran...
          Progreso          Pisano 2007 Etxe Oneko Fortified Sweet Red Tan...
          San Jose          Castillo Viejo 2005 El Preciado Gran Reserva R...
          Uruguay           Narbona NV Blend 002 Limited Edition Tannat-Ca...

                                          variety                winery
country   province
Argentina Mendoza Province                 Malbec  Bodega Catena Zapata
          Other                            Malbec                Colomé
Armenia   Armenia                            Rosé              Van Ardi
Australia Australia Other               Red Blend       Marquis Philips
          New South Wales                Sémillon            De Bortoli
...                                           ...                   ...
Uruguay   Juanico                       Red Blend        Familia Deicas
          Montevideo                    Red Blend                 Bouza
          Progreso                         Tannat                Pisano
          San Jose                      Red Blend        Castillo Viejo
          Uruguay           Tannat-Cabernet Franc               Narbona

[425 rows x 11 columns]

In [53]:
print("Under column len are the numbers of price occurences for each country like Argentina:",len(reviews.loc[reviews.country=="Argentina","price"]))
print(f"Get {reviews.groupby(["country"]).price.agg([len,"min","max"])}")

Under column len are the numbers of price occurences for each country like Argentina: 3800
Get                           len   min     max
country
Argentina                3800   4.0   230.0
Armenia                     2  14.0    15.0
Australia                2329   5.0   850.0
Austria                  3345   7.0  1100.0
Bosnia and Herzegovina      2  12.0    13.0
Brazil                     52  10.0    60.0
Bulgaria                  141   8.0   100.0
Canada                    257  12.0   120.0
Chile                    4472   5.0   400.0
China                       1  18.0    18.0
Croatia                    73  12.0    65.0
Cyprus                     11  11.0    21.0
Czech Republic             12  15.0    45.0
Egypt                       1   NaN     NaN
England                    74  25.0    95.0
France                  22093   5.0  3300.0
Georgia                    86   9.0    40.0
Germany                  2165   5.0   775.0
Greece                    466   8.0    79.0
Hungary                   146  10.0   764.0
India                       9  10.0    20.0
Israel                    505   8.0   150.0
Italy                   19540   5.0   900.0
Lebanon                    35  13.0    75.0
Luxembourg                  6  16.0    30.0
Macedonia                  12  15.0    20.0
Mexico                     70   8.0   108.0
Moldova                    59   8.0    42.0
Morocco                    28  14.0    40.0
New Zealand              1419   7.0   130.0
Peru                       16  10.0    68.0
Portugal                 5691   5.0  1000.0
Romania                   120   4.0   320.0
Serbia                     12  15.0    42.0
Slovakia                    1  16.0    16.0
Slovenia                   87   7.0    90.0
South Africa             1401   5.0   330.0
Spain                    6645   4.0   770.0
Switzerland                 7  21.0   160.0
Turkey                     90  14.0   120.0
US                      54504   4.0  2013.0
Ukraine                    14   6.0    13.0
Uruguay                   109  10.0   130.0

In [29]:
df = pd.read_csv("Country.csv")
print(df,"\n")
print(f"Calculate mean of \"Age\" for the only countries France, Germany and Spain: \n{df.groupby("Country")["Age"].mean()}\n")
print(f"Count occurances for the only countries France, Germany and Spain: \n{df.groupby("Country")["Age"].count()}\n")
print(f"Calculate mean and minimum of \"Age\" and sum of salary for every country: \n{df.groupby("Country").agg({"Age":["mean", "min"],"Salary":["sum"]})}\n")
print(f"Calculate mean and minimum of \"Age\" and sum of salary for every country: \n{df.groupby("Country").agg(Age_stats=("Age", "mean"),Salary_sum=("Salary","sum"))}\n")

   Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

Calculate mean of "Age" for the only countries France, Germany and Spain:
Country
France     41.0
Germany    40.0
Spain      32.5
Name: Age, dtype: float64

Count occurances for the only countries France, Germany and Spain:
Country
France     4
Germany    3
Spain      2
Name: Age, dtype: int64

Calculate mean and minimum of "Age" and sum of salary for every country:
          Age          Salary
         mean   min       sum
Country
France   41.0  35.0  276000.0
Germany  40.0  30.0  137000.0
Spain    32.5  27.0  161000.0

Calculate mean and minimum of "Age" and sum of salary for every country:
         Age_stats  Salary_sum
Country
France        41.0    276000.0
Germany       40.0    137000.0
Spain         32.5    161000.0

In [56]:
print(f"Multiindex:\n")
reviews.groupby(["country","province"]).description.agg([len])

Multiindex:

                             len
country   province
Argentina Mendoza Province  3264
          Other              536
Armenia   Armenia              2
Australia Australia Other    245
          New South Wales     85
...                          ...
Uruguay   Juanico             12
          Montevideo          11
          Progreso            11
          San Jose             3
          Uruguay             24

[425 rows x 1 columns]

# <u>Sorting</u>

```python
# Sort rows by a column
df.sort_values(by="age",axis,na_position,key)

# Descending
df.sort_values(by="age", ascending=False)

# Sort by multiple columns
df.sort_values(["city", "age"])

# Different order per column
df.sort_values(['dept', 'salary'], ascending=[True, False])

# Handle NaNs
df.sort_values('salary', na_position='first')

# In-place sort (usually avoid since chaining becomes harder)
df.sort_values('salary', inplace=True)

# Sort by row labels
df.sort_index()

# Sort columns by name
df.sort_index(axis=1)

# MultiIndex sorting
df.sort_index(level=0)

```

In [62]:
df = pd.read_csv("Country.csv")
print(df, "\n")
print(f"Sorted by column \"Age\" and NaN are put last:\n{df.sort_values(by="Age")}\n")

   Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

Sorted by column "Age" and NaN are put last:
   Country   Age   Salary Purchased
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
5   France  35.0  58000.0       Yes
9   France  37.0  67000.0       Yes
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
0   France  44.0  72000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
6    Spain   NaN  52000.0        No

In [61]:
print(f"Sorted by column \"Age\" reverse and NaN are put last:\n{df.sort_values("Age", ascending=False)}\n")
print(f"Sorted by columns \"Salary\" (first) and \"Age\" and NaN are put last:\n{df.sort_values(["Salary", "Age"])}\n")

Sorted by column "Age" reverse and NaN are put last:
   Country   Age   Salary Purchased
8  Germany  50.0  83000.0        No
7   France  48.0  79000.0       Yes
0   France  44.0  72000.0        No
4  Germany  40.0      NaN       Yes
3    Spain  38.0  61000.0        No
9   France  37.0  67000.0       Yes
5   France  35.0  58000.0       Yes
2  Germany  30.0  54000.0        No
1    Spain  27.0  48000.0       Yes
6    Spain   NaN  52000.0        No

Sorted by columns "Salary" (first) and "Age" and NaN are put last:
   Country   Age   Salary Purchased
1    Spain  27.0  48000.0       Yes
6    Spain   NaN  52000.0        No
2  Germany  30.0  54000.0        No
5   France  35.0  58000.0       Yes
3    Spain  38.0  61000.0        No
9   France  37.0  67000.0       Yes
0   France  44.0  72000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
4  Germany  40.0      NaN       Yes