# <u>Data Types</u>

```python
# Returns data type of every column
df.dtypes

# change data type in column "col" to data tyype float
df["col"] = df["col"].astype(float)

# The subset of the frame including the dtypes in include and excluding the dtypes in exclude
df.select_dtypes(include='number',exclude='bool')
```

In [10]:
import pandas as pd
reviews = pd.read_csv("winemag-data-130k-v2.csv",index_col=0)

In [20]:
print(f"Data Type of column \"price\" is {reviews["price"].dtype}\n")
print(f"Data Types of every columns are\n{reviews.dtypes}\n")
print(f"Convert datatype of column \"points\"\n{reviews["points"].astype("float64")}\n")
print(f"Convert datatypes of columns \"ponts\" and \"price\":\n")
reviews.astype({"points":"complex", "price":"bool"})

Data Type of column "price" is float64

Data Types of every columns are
country                   object
description               object
designation               object
points                     int64
price                    float64
province                  object
region_1                  object
region_2                  object
taster_name               object
taster_twitter_handle     object
title                     object
variety                   object
winery                    object
dtype: object

Convert datatype of column "points"
0         87.0
1         87.0
2         87.0
3         87.0
4         87.0
          ...
129966    90.0
129967    90.0
129968    90.0
129969    90.0
129970    90.0
Name: points, Length: 129971, dtype: float64

Convert datatypes of columns "ponts" and "price":

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87.0+ 0.0j,True,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia
1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87.0+ 0.0j,True,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos
2,US,"Tart and snappy, the flavors of lime flesh and...",NaN,87.0+ 0.0j,True,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Rainstorm 2013 Pinot Gris (Willamette Valley),Pinot Gris,Rainstorm
3,US,"Pineapple rind, lemon pith and orange blossom ...",Reserve Late Harvest,87.0+ 0.0j,True,Michigan,Lake Michigan Shore,NaN,Alexander Peartree,NaN,St. Julian 2013 Reserve Late Harvest Riesling ...,Riesling,St. Julian
4,US,"Much like the regular bottling from 2012, this...",Vintner's Reserve Wild Child Block,87.0+ 0.0j,True,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Sweet Cheeks 2012 Vintner's Reserve Wild Child...,Pinot Noir,Sweet Cheeks
...,...,...,...,...,...,...,...,...,...,...,...,...,...
129966,Germany,Notes of honeysuckle and cantaloupe sweeten th...,Brauneberger Juffer-Sonnenuhr Spätlese,90.0+ 0.0j,True,Mosel,NaN,NaN,Anna Lee C. Iijima,NaN,Dr. H. Thanisch (Erben Müller-Burggraef) 2013 ...,Riesling,Dr. H. Thanisch (Erben Müller-Burggraef)
129967,US,Citation is given as much as a decade of bottl...,NaN,90.0+ 0.0j,True,Oregon,Oregon,Oregon Other,Paul Gregutt,@paulgwine,Citation 2004 Pinot Noir (Oregon),Pinot Noir,Citation
129968,France,Well-drained gravel soil gives this wine its c...,Kritt,90.0+ 0.0j,True,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Gresser 2013 Kritt Gewurztraminer (Als...,Gewürztraminer,Domaine Gresser
129969,France,"A dry style of Pinot Gris, this is crisp with ...",NaN,90.0+ 0.0j,True,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Marcel Deiss 2012 Pinot Gris (Alsace),Pinot Gris,Domaine Marcel Deiss
129970,France,"Big, rich and off-dry, this is powered by inte...",Lieu-dit Harth Cuvée Caroline,90.0+ 0.0j,True,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Schoffit 2012 Lieu-dit Harth Cuvée Car...,Gewürztraminer,Domaine Schoffit

In [18]:
print(f"Index object of reviews dataframe\n{reviews.index}")
print(f"Data Type of the Index object of reviews dataframe:{reviews.index.dtype}")
print(f"Subset of dataframe with datatype in \"include\":\n{reviews.select_dtypes(include="number")}")

Index object of reviews dataframe
Index([     0,      1,      2,      3,      4,      5,      6,      7,      8,
            9,
       ...
       129961, 129962, 129963, 129964, 129965, 129966, 129967, 129968, 129969,
       129970],
      dtype='int64', length=129971)
Data Type of the Index object of reviews dataframe:int64
Subset of dataframe with datatype in "include":
        points  price
0           87    NaN
1           87   15.0
2           87   14.0
3           87   13.0
4           87   65.0
...        ...    ...
129966      90   28.0
129967      90   75.0
129968      90   30.0
129969      90   32.0
129970      90   21.0

[129971 rows x 2 columns]

# <u>Missing Values</u>

| Action         | Code                        |
| -------------- | --------------------------- |
| detect missing | `df.isna()`                 |
| detect non missing | `df.notna()`           |
| detect missing | `df.isnull()`               |
| detect noin missing |  `df.notnull()`        |
| fill missing with value  | `df.fillna(value,method='ffill',axis)`|
| drop column           | `df.drop("col", axis=1, inplace = False)`     |
| drop column and update df           | `df.drop("col", axis=1, inplace = True)`     |
| drop multiple columns | `df.drop(subset=["A","B"], axis=1, inplace = False)` |
| drop row              | `df.drop(3)`                 |
| drop NA rows          | `df.dropna()`                |
| drop rows with only Nas          | `df.dropna(how="all")`                |
| drop NA columns       | `df.dropna(axis=1)`          |
| drop NA rows       | `df.dropna(axis=0)`          |

In [42]:
df = pd.read_csv("Country.csv")
print(f"{df}\n")
print("Drop column \"Purchased\" but leave df unchanged: \n",df.drop("Purchased", axis=1))

   Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

Drop column "Purchased" but leave df unchanged:
    Country   Age   Salary
0   France  44.0  72000.0
1    Spain  27.0  48000.0
2  Germany  30.0  54000.0
3    Spain  38.0  61000.0
4  Germany  40.0      NaN
5   France  35.0  58000.0
6    Spain   NaN  52000.0
7   France  48.0  79000.0
8  Germany  50.0  83000.0
9   France  37.0  67000.0

In [35]:
print("Drop columns \"Purchased\" and \"Age\" but leave df unchanged: \n",df.drop(["Purchased", "Age"], axis=1),"\n")
print("Drop fourth row but leave df unchanged: \n",df.drop(4, axis=0))

Drop columns "Purchased" and "Age" but leave df unchanged:
    Country   Salary
0   France  72000.0
1    Spain  48000.0
2  Germany  54000.0
3    Spain  61000.0
4  Germany      NaN
5   France  58000.0
6    Spain  52000.0
7   France  79000.0
8  Germany  83000.0
9   France  67000.0

Drop fourth row but leave df unchanged:
    Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

In [36]:
print("Drop first and fourth row but leave df unchanged: \n",df.drop([1,4]),"\n")
print(f"Drop na rows: {df.dropna()}")

Drop first and fourth row but leave df unchanged:
    Country   Age   Salary Purchased
0   France  44.0  72000.0        No
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

Drop na rows:    Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
5   France  35.0  58000.0       Yes
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

In [37]:
print(f"Drop only complete na rows: {df.dropna(how="all")}")
print(df,"\n")
print(f"Drop na columns (\"Age\" and \"Salary\"): \n{df.dropna(axis=1)}")

Drop only complete na rows:    Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes
   Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

Drop na columns ("Age" and "Salary"):
   Country Purchased
0   France        No
1    Spain       Yes
2  Germany        No
3    Spain        No
4  Germany       Yes
5   France       Yes
6    Spain        No
7   France       Yes
8  Germany        No
9   France       Yes

In [38]:
print("Drop columns \"Purchased\" and \"Age\" and update df: \n",df.drop(["Purchased", "Age"], axis=1, inplace=True))
print(df)

Drop columns "Purchased" and "Age" and update df:
 None
   Country   Salary
0   France  72000.0
1    Spain  48000.0
2  Germany  54000.0
3    Spain  61000.0
4  Germany      NaN
5   France  58000.0
6    Spain  52000.0
7   France  79000.0
8  Germany  83000.0
9   France  67000.0

In [41]:
print(f"Detect missing values: \n{df.isna()}\n")
print(f"Fill missing values with 0: \n{df.fillna(0)}\n")
df

Detect missing values:
   Country  Salary
0    False   False
1    False   False
2    False   False
3    False   False
4    False    True
5    False   False
6    False   False
7    False   False
8    False   False
9    False   False

Fill missing values with 0:
   Country   Salary
0   France  72000.0
1    Spain  48000.0
2  Germany  54000.0
3    Spain  61000.0
4  Germany      0.0
5   France  58000.0
6    Spain  52000.0
7   France  79000.0
8  Germany  83000.0
9   France  67000.0

   Country   Salary
0   France  72000.0
1    Spain  48000.0
2  Germany  54000.0
3    Spain  61000.0
4  Germany      NaN
5   France  58000.0
6    Spain  52000.0
7   France  79000.0
8  Germany  83000.0
9   France  67000.0

In [48]:
df = pd.read_csv("Country.csv")
print(df,"\n")
print(f"Replace NaNs in multiple columns:\n{df.fillna({'Age': df['Age'].mean(),'Salary': 'Unknown'})}")

   Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

Replace NaNs in multiple columns:
   Country        Age   Salary Purchased
0   France  44.000000  72000.0        No
1    Spain  27.000000  48000.0       Yes
2  Germany  30.000000  54000.0        No
3    Spain  38.000000  61000.0        No
4  Germany  40.000000  Unknown       Yes
5   France  35.000000  58000.0       Yes
6    Spain  38.777778  52000.0        No
7   France  48.000000  79000.0       Yes
8  Germany  50.000000  83000.0        No
9   France  37.000000  67000.0       Yes

In [53]:
print(f"{df['Country'].where(df['Salary'] > 10000, "Good choice")}\n")
print(f"{df['Country'].mask(df['Salary'] > 10000, "Bad choice")}\n")

0         France
1          Spain
2        Germany
3          Spain
4    Good choice
5         France
6          Spain
7         France
8        Germany
9         France
Name: Country, dtype: object

0    Bad choice
1    Bad choice
2    Bad choice
3    Bad choice
4       Germany
5    Bad choice
6    Bad choice
7    Bad choice
8    Bad choice
9    Bad choice
Name: Country, dtype: object